on:
  push:
    branches: [ main ]

env:
  APTIBLE_ENVIRONMENT: ${{ secrets.APTIBLE_ENV }}
  APTIBLE_APP: ${{ secrets.APTIBLE_APP_HANDLE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.APTIBLE_GIT_SSH_KEY }}
      - name: Deploy to Aptible
        run: |
          ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
          git remote add aptible git@beta.aptible.com:${APTIBLE_ENVIRONMENT}/${APTIBLE_APP}.git
          git push aptible ${GITHUB_SHA}:master
